### ISSUE TITLE
integration tests are missing

### ISSUE THREAD

**Issue by yegor256** [objectionary/normalizer#3]
## Tasks

- [x] Use test files (depends on #13 )
- [x] Create a reproduction of the Pipeline (see below) in this repo in a `./pipeline` directory (@yegor256)
  - [x] provide necessary java files
  - [x] provide a bash script that runs the suggested pipeline
- [x] Build the package with `stack`

## Pipeline

The pipeline would be the following:

First, start with the `/tmp/test/app.eo` file:

```
[args] > app
  QQ.io.stdout > @
    "Hello, world!\n"
```

Then, compile it via [eoc](https://github.com/objectionary/eoc) and execute:

```
$ npm -g install eolang
$ cd /tmp/test
$ eoc dataize app
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
EO program assembled in .eoc
EO program verified in .eoc
Java sources generated in .eoc/generated-sources
Java .class files compiled into .eoc
Executable JAR created at .eoc/eoc.jar
Hello, world!

---
[1]
```

Then, generate the `.phi` file:

```
$ eoc phi
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
EO program assembled in .eoc
XMIR files converted into PHI files at .eoc
```

It will be generated in `.eoc/phi/app.phi`.

Then, normalize it and replace the `.eoc/phi/app.phi` file with new content (overwrite it!).

Then, generate XMIR from the `app.phi` file:

```
$ eoc unhpi
PHI files converted into XMIR files at .eoc/unphi
```

There should be new `.eoc/unphi/app.xmir` file generated.

Then, replace `.eoc/2-optimize/app.xmir` with this new file:

```bash
$ cp .eoc/unphi/app.xmir .eoc/2-optimize/app.xmir
```

Then, create a new EO file:

```
$ eoc print
XMIR files converted into EO files at .eoc/print
```

The `.eoc/print/app.eo` should be generated.

Copy it to `app.eo` (overwrite the existing one!):

```
$ cp .eoc/print/app.eo app.eo
```

Then, execute:

```
$ eoc clean
$ eoc dataize app
Hello, world!
```

Expect the `Hello, world!` output, as in the previous execution. If they match, your test passes.

**Comment by deemp** [comment]
- [ ] Decide on tests layout
  - probably in a `.yaml`
- [ ] Add sample tests
- [ ] Implement a Nix script to run tests with Java tools

**Comment by yegor256** [comment]
@deemp currently, this workflow doesn't work, due to this bug https://github.com/objectionary/eo/issues/2729

**Comment by deemp** [comment]
Please, provide a repo/gist with a bash script that runs the suggested workflow.

**Comment by yegor256** [comment]
@deemp see #3

**Comment by deemp** [comment]
Blocked by https://github.com/objectionary/eoc/issues/218
