### ISSUE TITLE
Create a `metrics` page on the site

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#370]
We need to refer to the documentation about metrics on some site pages and in the report.

## TODO

- [ ] Create a page `Metrics` on the site. The page should explain
  - [ ] the metrics that we use
  - [ ] why do we use these metrics
  - [ ] what improvements (relative changes w.r.t initial metrics) we want to achieve
  - [ ] where users can see reports
- [ ] Move the documentation about metrics from the report to the site. The report is generated by the normalizer ([link](https://github.com/objectionary/normalizer/blob/42fa5463e9f0af9580de3ce001f33aa4491d5df9/eo-phi-normalizer/src/Language/EO/Phi/Report/Html.hs)).
- [ ] Add links on the site where necessary
  - [ ] pipeline.md
