### ISSUE TITLE
Support enabling/disabling particular atoms

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#406]
## Details

- Related to #405

## Subtasks

- [x] Add `normalizer` options to disable/enable particular atoms.
- [x] Add `normalizer` commands to print arguments for the pipeline script.
- [x] Update pipeline config to use normalizer command that prints arguments.
- [ ] Update docs about normalizer options.
- [x] Update docs about pipeline config.
