### ISSUE TITLE
Set up a pipeline for a small java program

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#438]
## Details

We want to see the full pipeline for a single Java program in our CI.

We need Java -> Java bytecode -> EO -> PHI - Normalized PHI -> EO -> Java bytecode

## Subtasks

- [ ] Check progress on https://github.com/objectionary/normalizer/issues/379 https://github.com/objectionary/normalizer/issues/257 https://github.com/objectionary/normalizer/issues/256 issues
- [ ] Write a sample Java program with 2 + 2
- [ ] Write a user-defined rule to change 2 + 2 to 3 + 3
- [ ] Write a script to run translations
