### ISSUE TITLE
Replace `normalizer report` command with the `normalizer pipeline report` command

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#454]
## Details

Currently, the `normalizer report` command uses the pipeline config file for report generation.
Hence, this command should be moved into `normalizer pipeline` group of commands.

## Subtasks

- [x] Update the `normalizer pipeline` command
- [x] Update `normalizer report` documentation
- [x] Create a site subdirectory for `normalizer pipeline` commands
- [x] Move `normalizer report` documentation there
- [x] Update site docs config
