### ISSUE TITLE
Run mdbook in the pipeline job

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#457]
## Details

Currently, we use mdbook with `linkcheck` only on `master` ([link](https://github.com/objectionary/normalizer/blob/a970152a20373d1c33190495788bfe53e8869542/.github/workflows/ghc.yml#L346-L351)).

Therefore, if there are problems with `linkcheck`, the workflow on `master` will fail.

Hence, it's necessary to run `mdbook` with `linkcheck` in each pipeline.

## Subtasks

- [ ] Move the `mdbook` step to the `pipeline` job
- [ ] Save docs as an artifact
- [ ] Restore in the `docs` job

**Comment by 0crat** [comment]
@deemp Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -20 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [+93](https://www.eolang.org/zerocracy/objectionary-vitals.html).
