### ISSUE TITLE
Document how to run fourmolu without pre-commit

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#462]
## Details

Currently, there's only a script for running fourmolu via pre-commit.

https://github.com/objectionary/normalizer/blob/17dc8cbbba28b045f0c4640080df2251e6717861/site/docs/src/contributing.md?plain=1#L165

It'd be nice to have a script to run `fourmolu` without `pre-commit` while ignoring the same files as in the CI.
Then, contributors without `pre-commit` will also be able to run `fourmolu`.

## Subtasks

- [ ] Add a script for running `fourmolu`
- [ ] Make the script ignore the same files as in the CI
- [ ] Document in [contributing.md](https://github.com/objectionary/normalizer/blob/17dc8cbbba28b045f0c4640080df2251e6717861/site/docs/src/contributing.md)
