### ISSUE TITLE
Render LaTeX in CI

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#488]
## Details

Currently, we store `.png` files rendered from `normalizer` output in LaTeX.

- https://github.com/objectionary/normalizer/blob/9a640e95a1119605dbbba3881a0cd4a15d4e377e/site/docs/src/media/print-rules-tex-compact.png
- https://github.com/objectionary/normalizer/blob/9a640e95a1119605dbbba3881a0cd4a15d4e377e/site/docs/src/media/print-rules-tex.png

However, we'll have to update them manually when `yegor.yaml` changes.

## Subtasks

- [ ] Compose a `LaTeX` file with necessary code and generated rules
- [ ] Render it via a CLI
- [ ] Add to CI
- [ ] Add caching
